### ISSUE TITLE
Unable to run export_dashboard.py

### ISSUE THREAD

**Issue by sinagarajan** [signalfx/built-in-dashboards#12]
I have a requirement to convert the SignalFX dashboards into code. I wanted to modify all my dashboards into terraform code and I followed the guidelines mentioned in Readme file . 

```
python export_dashboards.py --key <<>> --api_url=https://api.us2.signalfx.com --dashboard EUfpCbjA8AA --name test --output ./
  File "export_dashboards.py", line 26
	tffile.write(f'\tauth_token = "{key}"\n')
```

This is the error I'm getting . Can you let me know why I'm facing this issue ? 

Also, I see some libraries like signalfx is already included . 
https://github.com/signalfx/built-in-dashboards/blob/master/export_dashboards.py#L5
Can you elaborate on detailed steps to be done before executing the code in the README file ?

**Comment by cory-signalfx** [comment]
Hey @sinagarajan!

Unfortunately your paste is missing the error, but if I had to guess it's because you're not using Python 3.

I'm updated the Readme to [include some help on venv and python3](https://github.com/signalfx/built-in-dashboards#requirements). If you follow those and use Python 3 you should be good to go!
