### ISSUE TITLE
Data Links are not generated

### ISSUE THREAD

**Issue by sinagarajan** [signalfx/built-in-dashboards#17]
We have dashboards with data links that link to another dashboard within the same group. The tf file dont contain any reference to data links .

Is the work still in progress ?

**Comment by cory-signalfx** [comment]
Hey @sinagarajan,

I wouldn't call it a work in progress so much as "oops, i guess that's true". 😄 

The reason this isn't working at present is that data links are a separate entity. That requires doing a bit more digging. I'll look into this!

**Comment by cory-signalfx** [comment]
I will try and have this done next week.

**Comment by cory-signalfx** [comment]
Hey @sinagarajan, I don't think this is going to happen. This is one of those slippery slope situations…

I did some work today and could make this happen, but the issue is the "target" of the link will stay as a static set of ids, for example:

```
# signalfx_data_link.farts_data_link_0:
resource "signalfx_data_link" "farts_data_link_0" {
    context_dashboard_id = "EFt8R64AcAA"
    property_name        = "host"

    target_signalfx_dashboard {
        dashboard_group_id = "EPpJWL_AcAA"
        dashboard_id       = "EP4Kz5tAYAA"
        is_default         = true
        name               = "ZXZX"
    }
}
```

The `target_signalfx_dashboard` will not be converted into a Terraform resource, because we don't know anything about. It's possible in an intra-group link to spot them.

As a result I plan to leave this feature out. I will extend the documentation to explain the reasoning.
